"""Renaming event_id to google_calendar_event_id

Revision ID: 3102fcfc5db8
Revises: 5f83a23d61d5
Create Date: 2021-04-07 13:06:06.496846

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3102fcfc5db8'
down_revision = '5f83a23d61d5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('event', sa.Column('google_calendar_event_id', sa.String(length=1024), nullable=True))
    op.drop_index('ix_event_event_id', table_name='event')
    op.create_index(op.f('ix_event_google_calendar_event_id'), 'event', ['google_calendar_event_id'], unique=True)
    op.drop_column('event', 'event_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('event', sa.Column('event_id', sa.VARCHAR(length=1024), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_event_google_calendar_event_id'), table_name='event')
    op.create_index('ix_event_event_id', 'event', ['event_id'], unique=True)
    op.drop_column('event', 'google_calendar_event_id')
    # ### end Alembic commands ###
