"""Adding document_link and conference_link into Event

Revision ID: 8fba12a7bb54
Revises: e594abb9d50c
Create Date: 2021-05-28 12:02:10.319800

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8fba12a7bb54'
down_revision = 'e594abb9d50c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('event', sa.Column('conference_link', sa.String(length=2000), nullable=True))
    op.add_column('event', sa.Column('document_link', sa.String(length=2000), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('event', 'document_link')
    op.drop_column('event', 'conference_link')
    # ### end Alembic commands ###
