"""Add BaseModel and UserModel

Revision ID: a7ece426b5dc
Revises: 8b4b8dbe7045
Create Date: 2021-03-31 22:45:19.761410

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a7ece426b5dc'
down_revision = '8b4b8dbe7045'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('active', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('archived', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('chat_id', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('first_name', sa.String(), nullable=True))
    op.add_column('users', sa.Column('is_bot', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('language_code', sa.String(), nullable=True))
    op.add_column('users', sa.Column('last_name', sa.String(), nullable=True))
    op.add_column('users', sa.Column('timestamp', sa.DateTime(), nullable=True))
    op.add_column('users', sa.Column('username', sa.String(), nullable=True))
    op.create_index(op.f('ix_users_chat_id'), 'users', ['chat_id'], unique=True)
    op.drop_column('users', 'name')
    op.drop_column('users', 'telegram_chat_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('telegram_chat_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_users_chat_id'), table_name='users')
    op.drop_column('users', 'username')
    op.drop_column('users', 'timestamp')
    op.drop_column('users', 'last_name')
    op.drop_column('users', 'language_code')
    op.drop_column('users', 'is_bot')
    op.drop_column('users', 'first_name')
    op.drop_column('users', 'chat_id')
    op.drop_column('users', 'archived')
    op.drop_column('users', 'active')
    # ### end Alembic commands ###
