"""Install. Using BaseModel in models through mixins

Revision ID: b51c63cb3539
Revises: 
Create Date: 2021-06-01 14:29:49.595311

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "b51c63cb3539"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
