"""Added some_field for test alembic

Revision ID: 581e668f747c
Revises: 83767a73fe1b
Create Date: 2022-01-06 13:40:49.913112

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "581e668f747c"
down_revision = "83767a73fe1b"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "user", sa.Column("somme_field", sa.String(length=50), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("user", "somme_field")
    # ### end Alembic commands ###
