"""Added some_field for test alembic

Revision ID: 6cf22634179a
Revises: c432c0b92b57
Create Date: 2022-01-06 23:52:14.728804

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6cf22634179a'
down_revision = 'c432c0b92b57'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('somme_field', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'somme_field')
    # ### end Alembic commands ###
