"""Deleted some_field for test alembic

Revision ID: c432c0b92b57
Revises: 581e668f747c
Create Date: 2022-01-06 23:08:37.577143

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c432c0b92b57'
down_revision = '581e668f747c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'somme_field')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('somme_field', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
